kubeconfig: "{{ lookup('env', 'KUBECONFIG')  }}"

# host paths

# path for typical config files like admin.conf
conf_path: /etc/kubernetes

# path to k8s certs
cert_path: /srv/kubernetes

# path to k8s pki
pki_path: /etc/kubernetes/pki

# path for k8s manifests e.g. kube-apiserver.manifest
manifest_path: /etc/kubernetes/manifests

# path to kubelet config
conf_path_kubelet: /etc/sysconfig

# path to etcd files
etcd_path: /var/lib/etcd


# k8s manifests file names
controllermanager_manifest: kube-controller-manager.manifest
apiserver_manifest: kube-apiserver.manifest
scheduler_manifest: kube-scheduler.manifest
etcd_manifest: etcd-main.manifest
proxy_manifest: kube-proxy.manifest


# files
kubeadm: /usr/bin/kubeadm
kubelet: kubelet
kubeconfig_proxy: /var/lib/kube-proxy/kubeconfig
audit_policy_file: /srv/kubernetes/audit/policy-config.yaml


