kubeconfig: "{{ lookup('env', 'KUBECONFIG')  }}"

# paths
base_dir: "/etc/kubernetes"
k8s_dir: "/etc/kubernetes/manifests"
etcd_dir: "/etc/kubernetes/manifests"
etcd_data_dir: "/var/lib/etcd"
kubelet_dir: "/etc/sysconfig"
pki_dir: "/etc/kubernetes/pki"
kubectl_dir: "/var/lib"

# manifests
kube_proxy_manifest: "kube-proxy.manifest"
kubelet_manifest: "kubelet"
kube_apiserver_manifest: "kube-apiserver.manifest"
kube_controller_manager_manifest: "kube-controller-manager.manifest"
kube_scheduler_manifest: "kube-scheduler.manifest"
etcd_main_manifest: "etcd-main.manifest"


kubectl:
  vol: "/usr/bin/kubectl"
  mnt: "/tmp/bin/kubectl"